# Generated by Django 4.2.1 on 2023-06-01 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='iphone 8', max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('storage', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
